### ISSUE TITLE
heroku project - Caused by: java.lang.ClassNotFoundException: Main

### ISSUE THREAD

**Issue by armoucar** [caelum/vraptor-scaffold#67]
i was following the wiki - Slides deploy vraptor-scaffold apps on heroku #pt - to push a application to heroku but i wasn't effective.
A exception regarding the main class is ocurring.

Here:

2011-11-01T12:30:11+00:00 heroku[web.1]: Starting process with command `sh target/bin/webapp`
2011-11-01T12:30:11+00:00 app[web.1]: Exception in thread "main" java.lang.NoClassDefFoundError: Main
2011-11-01T12:30:11+00:00 app[web.1]: Caused by: java.lang.ClassNotFoundException: Main
2011-11-01T12:30:11+00:00 app[web.1]:   at java.net.URLClassLoader$1.run(URLClassLoader.java:217)
2011-11-01T12:30:11+00:00 app[web.1]:   at java.security.AccessController.doPrivileged(Native Method)
2011-11-01T12:30:11+00:00 app[web.1]:   at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
2011-11-01T12:30:11+00:00 app[web.1]:   at java.lang.ClassLoader.loadClass(ClassLoader.java:321)
2011-11-01T12:30:11+00:00 app[web.1]:   at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
2011-11-01T12:30:11+00:00 app[web.1]:   at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
2011-11-01T12:30:11+00:00 app[web.1]: Could not find the main class: Main. Program will exit.

Can you test it?

**Comment by armoucar** [comment]
when executing 'sh target/bin/webapp' locally, the error persists.

Exception in thread "main" java.lang.NoClassDefFoundError: Main
Caused by: java.lang.ClassNotFoundException: Main
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

**Comment by rodolfoliviero** [comment]
maybe something change on heroku. I reproduced the error here and I will investigate the problem. 
Thanks
